.TH "Collection" 3 "Sat Jan 12 2013" "p2p-distrubuted" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhashTable< key, value >\fP, \fBhashTable< key, typename list< value >::iterator >\fP, and \fBlru_map< key, value >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBgetSize\fP () const "
.br
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for p2p-distrubuted from the source code.
