.TH "dictionary< key, value >" 3 "Mon Jan 14 2013" "p2p-distrubuted" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dictionary< key, value > \- 
.PP
abstract class for dictionary ADT /**  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dictionary\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinsert\fP (const key &k, const value &v)=0"
.br
.ti -1c
.RI "virtual void \fBremove\fP (const key &k)=0"
.br
.ti -1c
.RI "virtual const value & \fBlookup\fP (const key &k)=0  throw (out_of_range)"
.br
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class key, class value>class dictionary< key, value >"
abstract class for dictionary ADT /** 

\fBAuthor:\fP
.RS 4
Vicente Adolfo Bolea Sanchez <vicente.bolea@gmail.com>, <vicente@unist.ac.kr> 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for p2p-distrubuted from the source code\&.
