.TH "/home/vicente/Documents/desarrollo/p2p_distributed/include/lru/lru_map.hh" 3 "Sun Jan 13 2013" "p2p-distrubuted" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vicente/Documents/desarrollo/p2p_distributed/include/lru/lru_map.hh \- 
.PP
abstract class for dictionary ADT -------------------------------------------------------  

.SH SYNOPSIS
.br
.PP
\fC#include <collection.hh>\fP
.br
\fC#include <hashtable.hh>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <list>\fP
.br
\fC#include <lru_map.tcc>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlru_map< key, value >\fP"
.br
.RI "\fITemplate header for \fBlru_map\fP ADT. \fP"
.in -1c
.SH "Detailed Description"
.PP 
abstract class for dictionary ADT ------------------------------------------------------- 

------------------------------------------------------- 
.PP
\fBAuthor:\fP
.RS 4
Vicente Adolfo Bolea Sanchez <vicente.bolea@gmail.com>, <vicente@unist.ac.kr> 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for p2p-distrubuted from the source code.
